### ISSUE TITLE
Cor - vermelho

### ISSUE THREAD

**Issue by alissonkissel** [lsa-pucrs/donnie-assistive-robot-sw#104]
Ao utilizar o comando "espiar", na posição [17,10,90], temos o retorno de todos os objetos corretamente (2 Verdes, 2 azuis e 1 vermelho). Ao dar o comando "falar cor vermelho" na mesma posição, o retorno está sendo "nenhum objeto encontrado com a cor vermelho. 0".
Segue o print demonstrando o bug.

Qualquer dúvida, podemos demonstrar pessoalmente.
![bug_cor_verm](https://cloud.githubusercontent.com/assets/28358763/26423440/199c692c-40a4-11e7-991d-132dd66916fa.png)

**Comment by amamory** [comment]
a modelagem de camera no Stage não é muito boa mesmo e tem sérias limitações. É um compromisso entre desempenho e precisão. O Stage foi feito p ser rápido, mas não preciso.
Este tipo de limitação é intrísica e não deve ser considerada um bug do Donnie.

ps.: possivelmente se a mesa estivesse na frente das cadeiras ele detectaria. mesmo assim, este tipo de erro eh normal e deve ser ignorado. Ajustem o cenário para que ele minimize este tipo de situação.
