### ISSUE TITLE
Atualização Ubuntu de 14.04 para 16.04

### ISSUE THREAD

**Issue by alissonkissel** [lsa-pucrs/donnie-assistive-robot-sw#105]
Com o Orca funcionando de forma insatisfatória no notebook utilizado em teste, GISKARD02, é necessário atualizar o Ubuntu para que seja atualizado o Orca, pois não tem como atualizar somente o Orca.
O notebook está com o Ubuntu 14.04 LTS

**Comment by amamory** [comment]
Joice está testando todo o ambiente no Ubuntu 16.04 LTS. Assim q terminar os testes vcs podem criar uma nova particao do computador para instalar o Ubuntu 16.04 LTS. O Marques e/ou Daniel sabem fazer isso. só não apaguem a partição antiga, com Ubuntu 14.04 LTS.

**Comment by amamory** [comment]
commit  26064ce is working with 16.04. Although, it is is not fully tested by users yet.
