### ISSUE TITLE
Comando Espiar - ter um buffer 

### ISSUE THREAD

**Issue by julianadamasio** [lsa-pucrs/donnie-assistive-robot-sw#106]
Quando o usuário digita ESPIAR e em seguida digita Espiar novamente, o sistema faz toda a execução do espiar. Seria interessante, ter um buffer para armazenar somente o último feedback dado ao usuário e então ao invés de executar tudo, somente trazer esse feedback. Mas isso, se o usuário não tiver realizado nenhuma outra ação como PF e GD. Ou seja, o robô estando na mesma posição de quando foi executado o primeiro ESPIAR. Assim, ficará mais rápido para o usuário, que não precisará escutar o robô escaniando todo o ambiente de novo.  (Isso foi uma reclamação na avaliação)

**Comment by amamory** [comment]
solucao não recomendada pois vai comecar a gerar vários casos de exceção. O melhor é investigar como acelerar estes dois comandos ou se é possivel fazer uma versao 'espiar -rapido', que seria a versao turbo do espiar.
