### ISSUE TITLE
Comando ESPIAR e COR

### ISSUE THREAD

**Issue by paulasaicosque** [lsa-pucrs/donnie-assistive-robot-sw#111]
Ao usar o comando ESPIAR e consequentemente o comando COR, o programa envia o erro "Segmentation fault (core dumped)" e fecha sozinho.
Segue imagens do que acontece:
![screenshot from 2018-04-02 12 55 09](https://user-images.githubusercontent.com/37882759/38209765-eb9f2440-36a4-11e8-81e9-a0553531312a.png)
![screenshot from 2018-04-02 15 27 12](https://user-images.githubusercontent.com/37882759/38209784-f81572d8-36a4-11e8-98b7-86fb177e8cd3.png)

**Comment by edutra** [comment]
Possível solução no devel, precisava-mos de alguem para testar.

**Comment by edutra** [comment]
Solucionado, vou fechar o ticket para organização.
