### ISSUE TITLE
internacionalizacao no interpretador GoDonnie

### ISSUE THREAD

**Issue by amamory** [lsa-pucrs/donnie-assistive-robot-sw#19]
suportar inicialmente en, pt-br. depois suportar es.

Uma opcao eh o uso de gettext
http://inti.sourceforge.net/tutorial/libinti/internationalization.html
https://mohan43u.wordpress.com/2012/07/02/gnu-gettext-yet-another-tutorial/

outra opcao
http://site.icu-project.org/

**Comment by rgmaidana** [comment]
Internacionalização e localização feitas.

Todos os módulos com mensagens de erro e logs foram internacionalizados, inicialmente apenas para en_US, utilizando a ferramenta gettext, cujos arquivos de localização encontram-se na pasta "root/resources/loc". Estes arquivos estão configurados para instalar junto ao sistema donnie na pasta indicada por "DONNIE_PATH".

Os comandos do interpretador foram localizados para inglês, e o usuário pode utilizar tanto em português quanto em inglês sem precisar recompilar.

Para selecionar o idioma (atualmente en_US e pt_BR), deve-se configurar a variável de ambiente DONNIE_LANG antes de rodar o sistema (donnie_player seguido de GoDonnie).
