### ISSUE TITLE
Speech não bufferiza as falas

### ISSUE THREAD

**Issue by marquesgh2m** [lsa-pucrs/donnie-assistive-robot-sw#83]
Ao mandar o speech narrar muito rápido(sem um delay) ele não fala as palavras intermediárias, só a primeira e a última.

para criar a=0; a<5; a=a+1 faça
falar a
fim para

**Comment by amamory** [comment]
este eh o comportamento esperado. neste caso o programados deve colocar um comando 'esperar' ao final de cada iteracao. favor testar a sugestao e fechar o bug.

**Comment by alissonkissel** [comment]
Se colocar o comando 'esperar', o speech vai falar "esperando x segundos". Este é o comportamento que será mantido?
