### ISSUE TITLE
Dúvidas quanto ao modo arquivo

### ISSUE THREAD

**Issue by julianadamasio** [lsa-pucrs/donnie-assistive-robot-sw#91]
Oi pessoal.
Qual extensão (por exemplo, .txt, .docx,, .gd) deve ser utilizada quando quero utilizar modo arquivo? Pode ser qualquer uma? 
O arquivo que quero usar na GoDonnie no modo arquivo pode ser salvo em qualquer local?
Se o arquivo for salvo na mesma pasta do projeto, é necessário colocar o caminho completo? Ou basta digitar GoDonnie –f square.gd

**Comment by julianadamasio** [comment]
Isso está no manual do sistema?

**Comment by joiceMarek** [comment]
Sim, inclui um exemplo para quando se está em diretórios diferentes.
