### ISSUE TITLE
Comando Cor e Espiar- detecta mais objetos do que existe no cenário.

### ISSUE THREAD

**Issue by julianadamasio** [lsa-pucrs/donnie-assistive-robot-sw#96]
Testei com o robô estando na posição inicial e com ele no meio do cenário.
falar cor verde
-- Existem 2 objetos verdes, é informado 3

falar cor azul
-- Existem 2 objetos azuis, é informado 3 

falar cor vermelho
-- Existe um objeto e é falado 1 corretamente. 

O espiar detecta mais objetos também segue print. 
![espiar_objetosamais](https://cloud.githubusercontent.com/assets/7702443/25201798/6aa53524-2529-11e7-94a1-ed47933ec8b5.png)

**Comment by DanielEinloft** [comment]
Problema de detectar mais blob foi resolvido. Implementação do espiar foi modificado também, agora espiando todo 180 graus e retornando as cores detectadas no final da execução do comando.
